# 
# Jekyll Configuration for https://thiamchi.github.io/CodeBlog/
# 
# jekyll -v > jekyll 3.8.5
#

# --- Site Setting ---

# The site's title
title: CodeBlog
email: thiamchi.gan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a Blog for recording my learning of C#, C++, Python and this Jekyll during my free time.

# Location from where the site will be served (repositoryname for GitHub Pages)
baseurl: /
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#url: https://thiamchi.github.io/CodeBlog

# Name of the GitHub repository (used to generating links to GitHub)
repository: thiamchi/CodeBlog

# --- Build settings ---

# Use Kramdown as the preferred Markdown parser
markdown: kramdown

# Exclude files
# exclude : []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Search for SASS files inside assets/sass
sass: { sass_dir: 'assets/sass' }

# Use jekyll-redirect-from to allow redirections
plugins:
  - jekyll-redirect-from

# --- Jekyll Locations ---
layouts_dir: _jekyll/layouts
includes_dir: _jekyll/includes

# --- Collections ---
collections:
  pages:
    output: true

# --- Defaults ---
defaults:
  - scope:
      path: "_pages"

permalink: :year-:month-:day-:title